/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Analyse an entire project and return a serialised `UniverseManifest` as JSON.
 *
 * Arguments:
 * - `file_entries_json`: JSON array of `{ path, source }` objects.
 * - `theme_json`: flattened theme map JSON.
 * - `config_json`: prop config map JSON.
 * - `group_registry_json`: group registry JSON (`{ "space": ["p", "px", ...], ... }`).
 * - `package_resolution_json`: JSON object mapping package specifiers to entry-point paths,
 *   e.g. `{ "@my-ui/components": "pkg-barrel/index.ts" }`. Pass `"{}"` when not needed.
 * - `prefix`: optional namespace prefix for class names and CSS custom properties.
 *   When set, `animus-` is replaced with `{prefix}-` in all generated identifiers.
 * - `emitter_config_json`: optional JSON `{ "runtime_import": "...", "css_module_id": "..." }`.
 *   Overrides hardcoded import paths in generated source. When `None`, defaults to
 *   `@animus-ui/system` and `virtual:animus/styles.css`.
 */
export declare function analyzeProject(fileEntriesJson: string, themeJson: string, variableMapJson: string, contextualVarsJson: string | undefined | null, configJson: string, groupRegistryJson: string, packageResolutionJson: string, devMode?: boolean | undefined | null, emitterConfigJson?: string | undefined | null, selectorAliasesJson?: string | undefined | null, selectorOrderJson?: string | undefined | null, globalStyleBlocksJson?: string | undefined | null): string

/**
 * Clear the per-file extraction cache used by `analyze_project()`.
 * Call this on geological resets (theme/config/system file change) to force
 * full re-analysis on the next `analyze_project()` call.
 */
export declare function clearAnalysisCache(): void

export declare function extract(source: string, filename: string, themeJson: string, variableMapJson: string, configJson: string, groupRegistryJson: string, selectorAliasesJson?: string | undefined | null, selectorOrderJson?: string | undefined | null): ExtractionResult

export interface ExtractionResult {
  css: string
  code: string
  sourceMap: string
  extractable: boolean
  errors: Array<string>
}

/**
 * Transform a single source file using a pre-built `UniverseManifest`.
 *
 * Looks up the file in the manifest, applies the pre-computed `createComponent`
 * replacements, and prepends the necessary runtime + CSS imports.
 */
export declare function transformFile(source: string, filename: string, manifestJson: string): TransformResult

/** Result of a single-file transform using a pre-built `UniverseManifest`. */
export interface TransformResult {
  code: string
  hasComponents: boolean
}
