import { defineConfig } from 'vite-plus';

const typescriptTestTargets = [
  'packages/system/__tests__',
  'packages/vite-plugin/tests',
  'packages/next-plugin/tests',
  'packages/properties/__tests__',
  'packages/_assertions/__tests__',
  'packages/_parity/__tests__',
  'scripts/verify/packed-graph.test.ts',
  'scripts/verify/owner-graph.test.ts',
  'scripts/verify/ci-graph.test.ts',
  'scripts/verify/preconditions.test.ts',
] as const;
const typescriptTestTargetArguments = typescriptTestTargets.join(' ');
const typescriptTestCommand = `bunx vp test run ${typescriptTestTargetArguments}`;
const typescriptCoverageExclusions = [
  '**/dist/**',
  'legacy/**',
  'packages/extract/index*.js',
  '**/__tests__/**',
  '**/tests/**',
  '**/__fixtures__/**',
] as const;
const typescriptCoverageExclusionArguments = typescriptCoverageExclusions
  .map((pattern) => `--coverage.exclude='${pattern}'`)
  .join(' ');

export default defineConfig({
  lint: {
    plugins: ['react', 'jsx-a11y', 'nextjs', 'import'],
    categories: {
      correctness: 'error',
      suspicious: 'error',
    },
    rules: {
      'react/react-in-jsx-scope': 'off',
      'import/no-unassigned-import': 'off',
      'react-hooks/exhaustive-deps': 'error',
      'react/no-array-index-key': 'error',
      'no-console': 'error',
      'no-underscore-dangle': 'off',
    },
    ignorePatterns: [
      '**/node_modules/**',
      '**/.next/**',
      '**/.animus/**',
      '**/.hygiene/**',
      '**/.wrangler/**',
      '**/.react-router/**',
      '**/dist/**',
      '**/build/**',
      '**/target/**',
      '**/tmp/**',
      'legacy/**',
      'e2e/next-app/next-env.d.ts',
      // OpenSpec CHANGE artifacts (journals, evidence tools) are
      // change-governed; schema executable scripts stay linted via the
      // override below.
      'openspec/changes/**',
    ],
    overrides: [
      {
        files: ['**/*.test-d.{ts,tsx}'],
        rules: {
          'no-unused-expressions': 'off',
          'jsx-a11y/prefer-tag-over-role': 'off',
        },
      },
      {
        files: ['packages/showcase/src/components/docs/ColorPalette.tsx'],
        rules: {
          'jsx-a11y/interactive-supports-focus': 'off',
          'jsx-a11y/prefer-tag-over-role': 'off',
        },
      },
      {
        files: ['packages/extract/tests/fixtures/**'],
        rules: {
          'no-unused-vars': 'off',
          'jsx-a11y/anchor-has-content': 'off',
          'react-hooks/exhaustive-deps': 'off',
        },
      },
      {
        // Schema-shipped CLI tooling: console IS the interface.
        files: ['openspec/schemas/**'],
        rules: {
          'no-console': 'off',
          'no-shadow': 'off',
        },
      },
      {
        // Parity harness is a CLI (scoreboard output) — console is its UI,
        // matching the scripts/** precedent below.
        files: [
          'packages/_parity/src/**',
          'packages/_parity/tools/**',
          'packages/_parity/corpus/**',
        ],
        rules: {
          'no-console': 'off',
          'no-unused-vars': 'off',
          // corpus fixtures deliberately exercise shadowing (usage-semantics family)
          'no-shadow': 'off',
        },
      },
      {
        files: ['scripts/**/*.ts', 'scripts/**/*.mjs', 'e2e/*/scripts/**/*.ts'],
        rules: {
          'no-console': 'off',
        },
      },
      {
        files: [
          'packages/next-plugin/src/**/*.ts',
          'packages/vite-plugin/src/**/*.ts',
        ],
        rules: {
          'no-console': 'off',
        },
      },
    ],
  },
  fmt: {
    semi: true,
    singleQuote: true,
    jsxSingleQuote: false,
    tabWidth: 2,
    printWidth: 80,
    trailingComma: 'es5',
    arrowParens: 'always',
    endOfLine: 'lf',
    bracketSpacing: true,
    bracketSameLine: false,
    useTabs: false,
    sortImports: {
      customGroups: [
        {
          groupName: 'react-libs',
          elementNamePattern: ['react', 'react-**'],
        },
      ],
      groups: [
        'react-libs',
        ['value-builtin', 'value-external'],
        'value-internal',
        ['value-parent', 'value-sibling', 'value-index'],
        'unknown',
      ],
    },
    ignorePatterns: [
      '**/node_modules/**',
      '**/.next/**',
      '**/.animus/**',
      '**/.hygiene/**',
      '**/.wrangler/**',
      '**/.react-router/**',
      '**/dist/**',
      '**/build/**',
      '**/target/**',
      // OpenSpec artifacts are schema-governed (brainstorm.md is immutable
      // once design.md exists); keep the repo formatter out of them.
      'openspec/**',
      '**/tmp/**',
      'legacy/**',
      // v2 NAPI loader surface is generated by napi build (same rationale
      // as the v1 pair above).
      'packages/extract/crates/extract-v2/index.js',
      'packages/extract/crates/extract-v2/index.d.ts',
      // Parity corpus fixtures are byte-precise adversarial inputs (e.g.
      // no-eof-newline.tsx); formatting would destroy their properties.
      'packages/_parity/corpus/**',
      'openspec/changes/archive/**/*.md',
    ],
  },
  test: {
    environment: 'happy-dom',
    exclude: [
      '**/node_modules/**',
      '**/dist/**',
      '**/cypress/**',
      '**/.{idea,git,cache,output,temp}/**',
      '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*',
      '**/legacy/**',
      '**/target/**',
      '**/.next/**',
      '**/.animus/**',
      '**/.hygiene/**',
      '**/.wrangler/**',
      '**/.react-router/**',
      '**/tmp/**',
    ],
  },
  run: {
    tasks: {
      'verify:lint': {
        command: 'bunx vp lint && bunx vp fmt --check',
        cache: false,
      },
      'verify:compile': {
        command: 'bash scripts/verify/compile.sh',
        cache: false,
      },
      'verify:types': {
        command: 'bash scripts/verify/types.sh',
        cache: false,
      },
      'verify:unit:rust': {
        command: 'bash scripts/verify/unit-rust.sh',
        cache: false,
      },
      'verify:clippy': {
        command: 'bash scripts/verify/clippy.sh',
        cache: false,
      },
      'verify:unit:ts': {
        command: typescriptTestCommand,
        cache: false,
      },
      'verify:coverage:ts': {
        command: `bunx vitest run ${typescriptTestTargetArguments} --coverage.enabled --coverage.provider=v8 --coverage.reporter=text --coverage.reporter=lcov --coverage.reportsDirectory=coverage/ts ${typescriptCoverageExclusionArguments}`,
        cache: false,
      },
      'verify:coverage:e2e': {
        command: 'bash scripts/verify/coverage-e2e.sh',
        cache: false,
      },
      'verify:workers:contracts': {
        command: 'bash scripts/verify/workers-contracts.sh',
        cache: false,
      },
      'verify:hygiene:rust': {
        command: 'bash scripts/verify/hygiene-rust.sh',
        cache: false,
      },
      'verify:canary': {
        command: 'bash scripts/verify/canary.sh',
        cache: false,
      },
      'verify:integration': {
        command: 'bash scripts/verify/integration.sh',
        cache: false,
      },
      'verify:assert:vinext': {
        command: 'vp run @animus-ui/vinext-app#verify:assert',
        cache: false,
      },
      'verify:assert:react-router': {
        command: 'vp run @animus-ui/react-router-app#verify:assert',
        cache: false,
      },
      'build:extract': {
        command: "bun run --filter '@animus-ui/extract' build",
        cache: false,
      },
      'build:extract-v2': {
        command: 'bash scripts/cloudflare/build-extract-v2.sh',
        cache: false,
      },
      'verify:parity': {
        command: 'bash scripts/verify/parity.sh',
        cache: false,
      },
      'verify:packed': {
        command: 'bash scripts/verify/packed.sh',
        cache: false,
      },
      'build:ts': {
        command: "bun run --filter './packages/*' build:ts",
        cache: false,
      },
      'build:all': {
        command: 'echo "build:all complete"',
        dependsOn: ['build:extract', 'build:ts'],
        cache: false,
      },
      build: {
        command: 'echo "build alias for build:ts"',
        dependsOn: ['build:ts'],
        cache: false,
      },

      verify: {
        command: 'echo "verify complete"',
        dependsOn: [
          'verify:lint',
          'verify:compile',
          'verify:types',
          'verify:unit:ts',
          'verify:unit:rust',
          'verify:clippy',
          'verify:canary',
          'verify:workers:contracts',
        ],
        cache: false,
      },
      'verify:full': {
        command:
          "vp run build:extract-v2 && vp run build:ts && vp run verify && vp run --fail-if-no-match -F './e2e/*' -F '!animus-packed-app' -F './packages/showcase' verify && vp run verify:parity && vp run verify:integration && vp run verify:hygiene:rust && vp run verify:packed",
        cache: false,
      },
      hygiene: {
        command: 'bash scripts/hygiene/run.sh',
        cache: false,
      },
      'test:run': {
        command: 'bunx vp test run',
        cache: false,
      },

      clean: {
        command:
          'rm -rf packages/*/dist packages/extract/crates/extract-v2/target packages/extract/crates/system-loader/target',
        cache: false,
      },
      'clean:light': {
        command: 'rm -rf node_modules/.vite packages/*/dist',
        cache: false,
      },
      'clean:full': {
        command:
          'rm -rf node_modules/.vite packages/*/dist packages/extract/crates/extract-v2/target packages/extract/crates/system-loader/target packages/extract/crates/extract-v2/*.node',
        cache: false,
      },
    },
  },
});
