import { defineConfig } from 'vite-plus';

export default defineConfig({
  lint: {
    plugins: ['react', 'jsx-a11y', 'nextjs', 'import'],
    categories: {
      correctness: 'error',
      suspicious: 'error',
    },
    rules: {
      'react/react-in-jsx-scope': 'off',
      'import/no-unassigned-import': 'off',
      'react-hooks/exhaustive-deps': 'error',
      'react/no-array-index-key': 'error',
      'no-console': 'error',
    },
    ignorePatterns: [
      '**/node_modules/**',
      '**/.next/**',
      '**/.animus/**',
      '**/.hygiene/**',
      '**/.wrangler/**',
      '**/.react-router/**',
      '**/dist/**',
      '**/build/**',
      '**/target/**',
      '**/tmp/**',
      'legacy/**',
      'packages/extract/index.js',
      'packages/extract/index.d.ts',
      'e2e/next-app/next-env.d.ts',
      // OpenSpec CHANGE artifacts (journals, evidence tools) are
      // change-governed; schema executable scripts stay linted via the
      // override below.
      'openspec/changes/**',
    ],
    overrides: [
      {
        files: ['**/*.test-d.{ts,tsx}'],
        rules: {
          'no-unused-expressions': 'off',
          'jsx-a11y/prefer-tag-over-role': 'off',
        },
      },
      {
        files: ['packages/extract/tests/fixtures/**'],
        rules: {
          'no-unused-vars': 'off',
          'jsx-a11y/anchor-has-content': 'off',
          'react-hooks/exhaustive-deps': 'off',
        },
      },
      {
        // Schema-shipped CLI tooling: console IS the interface.
        files: ['openspec/schemas/**'],
        rules: {
          'no-console': 'off',
          'no-shadow': 'off',
        },
      },
      {
        // Parity harness is a CLI (scoreboard output) — console is its UI,
        // matching the scripts/** precedent below.
        files: [
          'packages/_parity/src/**',
          'packages/_parity/tools/**',
          'packages/_parity/corpus/**',
        ],
        rules: {
          'no-console': 'off',
          'no-unused-vars': 'off',
          // corpus fixtures deliberately exercise shadowing (usage-semantics family)
          'no-shadow': 'off',
        },
      },
      {
        files: ['scripts/**/*.ts', 'e2e/*/scripts/**/*.ts'],
        rules: {
          'no-console': 'off',
        },
      },
      {
        files: [
          'packages/next-plugin/src/**/*.ts',
          'packages/vite-plugin/src/**/*.ts',
        ],
        rules: {
          'no-console': 'off',
        },
      },
    ],
  },
  fmt: {
    semi: true,
    singleQuote: true,
    jsxSingleQuote: false,
    tabWidth: 2,
    printWidth: 80,
    trailingComma: 'es5',
    arrowParens: 'always',
    endOfLine: 'lf',
    bracketSpacing: true,
    bracketSameLine: false,
    useTabs: false,
    sortImports: {
      customGroups: [
        {
          groupName: 'react-libs',
          elementNamePattern: ['react', 'react-**'],
        },
      ],
      groups: [
        'react-libs',
        ['value-builtin', 'value-external'],
        'value-internal',
        ['value-parent', 'value-sibling', 'value-index'],
        'unknown',
      ],
    },
    ignorePatterns: [
      '**/node_modules/**',
      '**/.next/**',
      '**/.animus/**',
      '**/.hygiene/**',
      '**/.wrangler/**',
      '**/.react-router/**',
      '**/dist/**',
      '**/build/**',
      '**/target/**',
      // OpenSpec artifacts are schema-governed (brainstorm.md is immutable
      // once design.md exists); keep the repo formatter out of them.
      'openspec/**',
      '**/tmp/**',
      'legacy/**',
      'packages/extract/index.js',
      'packages/extract/index.d.ts',
      // v2 NAPI loader surface is generated by napi build (same rationale
      // as the v1 pair above).
      'packages/extract/crates/extract-v2/index.js',
      'packages/extract/crates/extract-v2/index.d.ts',
      // Parity corpus fixtures are byte-precise adversarial inputs (e.g.
      // no-eof-newline.tsx); formatting would destroy their properties.
      'packages/_parity/corpus/**',
      'openspec/changes/archive/**/*.md',
    ],
  },
  test: {
    environment: 'happy-dom',
    exclude: [
      '**/node_modules/**',
      '**/dist/**',
      '**/cypress/**',
      '**/.{idea,git,cache,output,temp}/**',
      '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*',
      '**/legacy/**',
      '**/target/**',
      '**/.next/**',
      '**/.animus/**',
      '**/.hygiene/**',
      '**/.wrangler/**',
      '**/.react-router/**',
      '**/tmp/**',
    ],
  },
  run: {
    tasks: {
      'verify:lint': {
        command: 'bunx vp lint && bunx vp fmt --check',
        cache: false,
      },
      'verify:compile': {
        command: 'bash scripts/verify/compile.sh',
        cache: false,
      },
      'verify:types': {
        command: 'bash scripts/verify/types.sh',
        cache: false,
      },
      'verify:unit:rust': {
        command: 'bash scripts/verify/unit-rust.sh',
        cache: false,
      },
      'verify:unit:ts': {
        command:
          'bunx vp test run packages/system/__tests__ packages/vite-plugin/tests packages/next-plugin/tests packages/properties/__tests__ packages/_assertions/__tests__ packages/_parity/__tests__',
        cache: false,
      },
      'verify:workers:contracts': {
        command: 'bash scripts/verify/workers-contracts.sh',
        cache: false,
      },
      'verify:hygiene:rust': {
        command: 'bash scripts/verify/hygiene-rust.sh',
        cache: false,
      },
      'verify:canary': {
        command: 'bash scripts/verify/canary.sh',
        cache: false,
      },
      'verify:integration': {
        command: 'bash scripts/verify/integration.sh',
        cache: false,
      },
      'verify:build:next': {
        command: 'bash scripts/verify/build-next.sh',
        cache: false,
      },
      'verify:build:showcase': {
        command: 'bash scripts/verify/build-showcase.sh',
        cache: false,
      },
      'verify:build:vite': {
        command: 'bash scripts/verify/build-vite.sh',
        cache: false,
      },
      'verify:build:vinext': {
        command: 'bash scripts/verify/build-vinext.sh',
        cache: false,
      },
      'verify:build:react-router': {
        command: 'bash scripts/verify/build-react-router.sh',
        cache: false,
      },
      'verify:assert:next': {
        command: 'bash scripts/verify/assert-next.sh',
        cache: false,
      },
      'verify:assert:showcase': {
        command: 'bash scripts/verify/assert-showcase.sh',
        cache: false,
      },
      'verify:assert:vite': {
        command: 'bash scripts/verify/assert-vite.sh',
        cache: false,
      },
      'verify:assert:vinext': {
        command: 'bash scripts/verify/assert-vinext.sh',
        cache: false,
      },
      'verify:assert:react-router': {
        command: 'bash scripts/verify/assert-react-router.sh',
        cache: false,
      },
      'verify:dry-run:showcase': {
        command:
          "bash scripts/verify/dry-run-worker.sh packages/showcase '@animus-ui/showcase' packages/showcase/dist animus verify:build:showcase",
        cache: false,
      },
      'verify:dry-run:vite': {
        command:
          "bash scripts/verify/dry-run-worker.sh e2e/vite-app '@animus-ui/vite-app' e2e/vite-app/dist animus-vite-canary verify:build:vite",
        cache: false,
      },
      'verify:dry-run:vinext': {
        command:
          "bash scripts/verify/dry-run-worker.sh e2e/vinext-app '@animus-ui/vinext-app' e2e/vinext-app/dist animus-vinext-canary verify:build:vinext",
        cache: false,
      },
      'verify:dry-run:react-router': {
        command:
          "bash scripts/verify/dry-run-worker.sh e2e/react-router-app '@animus-ui/react-router-app' e2e/react-router-app/build animus-react-router-canary verify:build:react-router",
        cache: false,
      },
      '_verify:dry-run:showcase:after-build': {
        command:
          "bash scripts/verify/dry-run-worker.sh packages/showcase '@animus-ui/showcase' packages/showcase/dist animus verify:build:showcase",
        dependsOn: ['verify:build:showcase'],
        cache: false,
      },
      '_verify:dry-run:vite:after-build': {
        command:
          "bash scripts/verify/dry-run-worker.sh e2e/vite-app '@animus-ui/vite-app' e2e/vite-app/dist animus-vite-canary verify:build:vite",
        dependsOn: ['verify:build:vite'],
        cache: false,
      },
      '_verify:dry-run:vinext:after-build': {
        command:
          "bash scripts/verify/dry-run-worker.sh e2e/vinext-app '@animus-ui/vinext-app' e2e/vinext-app/dist animus-vinext-canary verify:build:vinext",
        dependsOn: ['verify:build:vinext'],
        cache: false,
      },
      '_verify:dry-run:react-router:after-build': {
        command:
          "bash scripts/verify/dry-run-worker.sh e2e/react-router-app '@animus-ui/react-router-app' e2e/react-router-app/build animus-react-router-canary verify:build:react-router",
        dependsOn: ['verify:build:react-router'],
        cache: false,
      },

      'build:extract': {
        command: "bun run --filter '@animus-ui/extract' build",
        cache: false,
      },
      'build:extract-v2': {
        command: "bun run --filter '@animus-ui/extract' build:v2",
        cache: false,
      },
      'verify:parity': {
        command: 'bash scripts/verify/parity.sh',
        cache: false,
      },
      'build:ts': {
        command: "bun run --filter './packages/*' build:ts",
        cache: false,
      },
      'build:all': {
        command: 'echo "build:all complete"',
        dependsOn: ['build:extract', 'build:ts'],
        cache: false,
      },
      'build:showcase': {
        command: "bun run --filter './packages/showcase' build",
        dependsOn: ['build:ts'],
        cache: false,
      },
      'build:vite': {
        command: "bun run --filter '@animus-ui/vite-app' build",
        dependsOn: ['build:ts'],
        cache: false,
      },
      'build:vinext': {
        command: "bun run --filter '@animus-ui/vinext-app' build",
        dependsOn: ['build:ts'],
        cache: false,
      },
      'build:react-router': {
        command: "bun run --filter '@animus-ui/react-router-app' build",
        dependsOn: ['build:ts'],
        cache: false,
      },
      build: {
        command: 'echo "build alias for build:ts"',
        dependsOn: ['build:ts'],
        cache: false,
      },

      verify: {
        command: 'echo "verify complete"',
        dependsOn: [
          'verify:lint',
          'verify:compile',
          'verify:types',
          'verify:unit:ts',
          'verify:unit:rust',
          'verify:canary',
          'verify:workers:contracts',
        ],
        cache: false,
      },
      'verify:full': {
        command: 'echo "verify:full complete"',
        dependsOn: [
          'verify:lint',
          'verify:compile',
          'verify:types',
          'verify:unit:ts',
          'verify:unit:rust',
          'verify:canary',
          'verify:workers:contracts',
          'verify:parity',
          'verify:integration',
          'verify:next',
          'verify:showcase',
          'verify:vite',
          'verify:vinext',
          'verify:react-router',
          '_verify:dry-run:showcase:after-build',
          '_verify:dry-run:vite:after-build',
          '_verify:dry-run:vinext:after-build',
          '_verify:dry-run:react-router:after-build',
        ],
        cache: false,
      },
      'verify:ci': {
        command: 'echo "verify:ci complete"',
        dependsOn: [
          'verify:lint',
          'verify:unit:rust',
          'verify:hygiene:rust',
          'build:extract',
          'build:ts',
          'verify:compile',
          'verify:types',
          'verify:unit:ts',
          'verify:workers:contracts',
          'verify:canary',
          'verify:parity',
          'verify:integration',
          'verify:showcase',
          'verify:vite',
          'verify:vinext',
          'verify:react-router',
          '_verify:dry-run:showcase:after-build',
          '_verify:dry-run:vite:after-build',
          '_verify:dry-run:vinext:after-build',
          '_verify:dry-run:react-router:after-build',
        ],
        cache: false,
      },
      'verify:next': {
        command: 'bash scripts/verify/assert-next.sh',
        dependsOn: ['verify:build:next'],
        cache: false,
      },
      'verify:showcase': {
        command: 'bash scripts/verify/assert-showcase.sh',
        dependsOn: ['verify:build:showcase'],
        cache: false,
      },
      'verify:vite': {
        command: 'bash scripts/verify/assert-vite.sh',
        dependsOn: ['verify:build:vite'],
        cache: false,
      },
      'verify:vinext': {
        command: 'bash scripts/verify/assert-vinext.sh',
        dependsOn: ['verify:build:vinext'],
        cache: false,
      },
      'verify:react-router': {
        command: 'bash scripts/verify/assert-react-router.sh',
        dependsOn: ['verify:build:react-router'],
        cache: false,
      },

      hygiene: {
        command: 'bash scripts/hygiene/run.sh',
        cache: false,
      },
      'test:run': {
        command: 'bunx vp test run',
        cache: false,
      },

      clean: {
        command: 'rm -rf packages/*/dist packages/extract/target',
        cache: false,
      },
      'clean:light': {
        command: 'rm -rf node_modules/.vite packages/*/dist',
        cache: false,
      },
      'clean:full': {
        command:
          'rm -rf node_modules/.vite packages/*/dist packages/extract/target packages/extract/*.node',
        cache: false,
      },
    },
  },
});
