/* auto-generated by NAPI-RS */
/* eslint-disable */

export declare class ExtractEngine {
  constructor(options?: EngineOptions | undefined | null)
  analyze(fileEntriesJson: string): string
  clearCache(): void
  get parseCount(): number
  transformFile(path: string): string
}

/**
 * Every diagnostic code the engine emits, with the severity it carries, as
 * JSON: `{ "animus.chain.unextractable": "warn", … }`. Hosts check codes
 * against it instead of keeping a table of their own.
 */
export declare function diagnosticCodes(): string

/**
 * Chain discovery over a file set: one parse per file, then one walk per
 * stored AST.
 */
export declare function discoverChains(fileEntriesJson: string): string

export interface EngineOptions {
  prefix?: string
  runtimeImport?: string
  cssModuleId?: string
  systemPropsModuleId?: string
  themeJson?: string
  variableMapJson?: string
  contextualVarsJson?: string
  /**
   * Declaration scales, `{ scale: { kind, members, values } }`; absent
   * means none.
   */
  declarationScalesJson?: string
  configJson?: string
  groupRegistryJson?: string
  transformSourcesJson?: string
  transformProvenanceJson?: string
  selectorAliasesJson?: string
  conditionAliasesJson?: string
  globalStyleBlocksJson?: string
  keyframesJson?: string
  packageResolutionJson?: string
  pathAliasesJson?: string
  staticCssJson?: string
  externalDirsJson?: string
  devMode?: boolean
  /**
   * What the host knows about renders the analysis cannot see:
   * `{ skippedSources, unbundledComputedImports, packageDirs }`, each
   * optional.
   */
  analysisContextJson?: string
  /**
   * Under a prefix, each name the theme generates and its final name,
   * without `--`: authored component styles take the final names.
   */
  generatedNamesJson?: string
}

/** Probe identity: proves the binary loads and its oxc linkage parses. */
export declare function engineVersion(): string

/**
 * Full per-file fact extraction, one parse per file. The store and its
 * ASTs drop on return: no `program()` read survives cross-file resolve.
 */
export declare function extractFacts(fileEntriesJson: string): string

export declare function loadSystemModule(systemPath: string, rootDir: string, exportName?: string | undefined | null): NapiSystemConfig

export interface NapiSystemConfig {
  propConfig: string
  groupRegistry: string
  scalesJson: string
  variableMapJson: string
  variableCss: string
  contextualVarsJson: string
  /**
   * Declaration scales JSON (`{ scale: { kind, members, values } }`);
   * pass it as `declarationScalesJson`. Absent when the theme has none.
   */
  declarationScalesJson?: string
  /**
   * Declared custom-property records JSON, sorted by name. Absent when
   * the theme declares none.
   */
  propertyRecordsJson?: string
  selectorAliases?: string
  selectorOrder?: string
  /**
   * Condition alias map JSON (the `conditionAliases` manifest field):
   * alias → `{ value, order, kind }`. Absent when none are registered.
   */
  conditionAliases?: string
  /**
   * Transform source texts by definition key (`{ transformId: sourceText }`
   * JSON): the only channel by which configured transforms reach evaluation.
   */
  transformSources?: string
  /**
   * Host-binding evidence by the same keys (`{ transformId: { hostGlobals:
   * [names] } | { rejection: reason } }` JSON), from each configured
   * transform's authored callable; pass it as `transformProvenanceJson`.
   * A reason completes "its callable …".
   */
  transformProvenance?: string
  globalStyleBlocks?: string
  keyframesBlocks?: string
  /**
   * Vocabulary witnesses as a JSON array of coded entries; hosts surface
   * each as a diagnostic keyed by its `code`. Absent when there are none.
   */
  vocabularyWitnesses?: string
  /**
   * Canonical absolute paths of every module evaluated for the system,
   * sorted; the entry is included, runtime stubs are not.
   */
  dependencies: Array<string>
  /**
   * Per-module built-theme token manifests, shaped
   * `{ modulePath: { exportName: [token paths] } }`. Absent when none exist.
   */
  sourceThemeManifests?: string
}
