/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class ExtractEngine {
  constructor(options?: EngineOptions | undefined | null)
  analyze(fileEntriesJson: string): string
  clearCache(): void
  get parseCount(): number
  transformFile(path: string): string
}

/**
 * Chain discovery over a file set: one parse per file, then one walk per
 * stored AST.
 */
export declare function discoverChains(fileEntriesJson: string): string

export interface EngineOptions {
  prefix?: string
  runtimeImport?: string
  cssModuleId?: string
  systemPropsModuleId?: string
  themeJson?: string
  variableMapJson?: string
  contextualVarsJson?: string
  configJson?: string
  groupRegistryJson?: string
  transformSourcesJson?: string
  selectorAliasesJson?: string
  conditionAliasesJson?: string
  globalStyleBlocksJson?: string
  keyframesJson?: string
  packageResolutionJson?: string
  pathAliasesJson?: string
  staticCssJson?: string
  externalDirsJson?: string
  devMode?: boolean
}

/** Probe identity: proves the binary loads and its oxc linkage parses. */
export declare function engineVersion(): string

/**
 * Full per-file fact extraction, one parse per file. The store and its
 * ASTs drop on return: no `program()` read survives cross-file resolve.
 */
export declare function extractFacts(fileEntriesJson: string): string

export declare function loadSystemModule(systemPath: string, rootDir: string, exportName?: string | undefined | null): NapiSystemConfig

export interface NapiSystemConfig {
  propConfig: string
  groupRegistry: string
  scalesJson: string
  variableMapJson: string
  variableCss: string
  contextualVarsJson: string
  selectorAliases?: string
  selectorOrder?: string
  /**
   * Condition alias map JSON (the `conditionAliases` manifest field):
   * alias → `{ value, order, kind }`. Absent when none are registered.
   */
  conditionAliases?: string
  /**
   * Transform source texts (`{ transformName: sourceText }` JSON): the
   * only channel by which transforms shipped in a package reach evaluation.
   */
  transformSources?: string
  globalStyleBlocks?: string
  keyframesBlocks?: string
  /**
   * Vocabulary witnesses as a JSON array of coded entries; hosts surface
   * each as a diagnostic keyed by its `code`. Absent when there are none.
   */
  vocabularyWitnesses?: string
  /**
   * Canonical absolute paths of every module evaluated for the system,
   * sorted; the entry is included, runtime stubs are not.
   */
  dependencies: Array<string>
  /**
   * Per-module built-theme token manifests, shaped
   * `{ modulePath: { exportName: [token paths] } }`. Absent when none exist.
   */
  sourceThemeManifests?: string
}
