/**
 * The properties whose intended value is a length, as style keys: on a
 * strict scale, zero (`0` or `'0'`) is admitted beside the scale's keys only
 * on these, and elsewhere the scale wins. A property is listed when its
 * syntax in mdn-data is built from lengths, length-percentages, line widths
 * and percentages, with keywords and length functions: margins, paddings,
 * gaps, insets, sizes, radii, border and outline widths, positions and
 * offsets, among them SVG geometry and a stroke's width, whose numbers are
 * user units. `fontSize` is listed too, and so are the vendor-prefixed
 * spellings of listed properties. A property whose number is a multiplier or
 * a count (`lineHeight`, `borderImageWidth`, `tabSize`), a shorthand that
 * also takes colours or styles, and grid track sizing are not. The strict
 * types read this table, as does the runtime resolver; the extractor reads
 * it through `property_table.json`.
 */
export const ZERO_LENGTH_PROPERTIES = [
  'MozBorderEndWidth',
  'MozColumnRuleWidth',
  'MozColumnWidth',
  'MozMarginEnd',
  'MozMarginStart',
  'MozOutlineRadius',
  'MozOutlineRadiusBottomleft',
  'MozOutlineRadiusBottomright',
  'MozOutlineRadiusTopleft',
  'MozOutlineRadiusTopright',
  'MozPaddingEnd',
  'MozPaddingStart',
  'MozPerspective',
  'MozTransformOrigin',
  'WebkitBorderBeforeWidth',
  'WebkitBorderBottomLeftRadius',
  'WebkitBorderBottomRightRadius',
  'WebkitBorderRadius',
  'WebkitBorderTopLeftRadius',
  'WebkitBorderTopRightRadius',
  'WebkitColumnRuleWidth',
  'WebkitColumnWidth',
  'WebkitFlexBasis',
  'WebkitLogicalHeight',
  'WebkitLogicalWidth',
  'WebkitMarginEnd',
  'WebkitMarginStart',
  'WebkitMaskPosition',
  'WebkitMaskPositionX',
  'WebkitMaskPositionY',
  'WebkitMaskSize',
  'WebkitMaxInlineSize',
  'WebkitPaddingEnd',
  'WebkitPaddingStart',
  'WebkitPerspective',
  'WebkitShapeMargin',
  'WebkitTextStrokeWidth',
  'WebkitTransformOrigin',
  'animationRangeEnd',
  'animationRangeStart',
  'backgroundPosition',
  'backgroundPositionX',
  'backgroundPositionY',
  'backgroundSize',
  'baselineShift',
  'blockSize',
  'borderBlockEndWidth',
  'borderBlockStartWidth',
  'borderBlockWidth',
  'borderBottomLeftRadius',
  'borderBottomRightRadius',
  'borderBottomWidth',
  'borderEndEndRadius',
  'borderEndStartRadius',
  'borderInlineEndWidth',
  'borderInlineStartWidth',
  'borderInlineWidth',
  'borderLeftWidth',
  'borderRadius',
  'borderRightWidth',
  'borderSpacing',
  'borderStartEndRadius',
  'borderStartStartRadius',
  'borderTopLeftRadius',
  'borderTopRightRadius',
  'borderTopWidth',
  'borderWidth',
  'bottom',
  'columnGap',
  'columnRuleWidth',
  'columnWidth',
  'containIntrinsicBlockSize',
  'containIntrinsicHeight',
  'containIntrinsicInlineSize',
  'containIntrinsicSize',
  'containIntrinsicWidth',
  'cx',
  'cy',
  'flexBasis',
  'fontSize',
  'gap',
  'height',
  'inlineSize',
  'inset',
  'insetBlock',
  'insetBlockEnd',
  'insetBlockStart',
  'insetInline',
  'insetInlineEnd',
  'insetInlineStart',
  'left',
  'letterSpacing',
  'lineHeightStep',
  'margin',
  'marginBlock',
  'marginBlockEnd',
  'marginBlockStart',
  'marginBottom',
  'marginInline',
  'marginInlineEnd',
  'marginInlineStart',
  'marginLeft',
  'marginRight',
  'marginTop',
  'maskPosition',
  'maskSize',
  'maxBlockSize',
  'maxHeight',
  'maxInlineSize',
  'maxWidth',
  'minBlockSize',
  'minHeight',
  'minInlineSize',
  'minWidth',
  'msHyphenateLimitZone',
  'msScrollLimitXMax',
  'msScrollLimitXMin',
  'msScrollLimitYMax',
  'msScrollLimitYMin',
  'msTransformOrigin',
  'msWrapMargin',
  'objectPosition',
  'offsetAnchor',
  'offsetDistance',
  'offsetPosition',
  'outlineOffset',
  'outlineWidth',
  'overflowClipMargin',
  'padding',
  'paddingBlock',
  'paddingBlockEnd',
  'paddingBlockStart',
  'paddingBottom',
  'paddingInline',
  'paddingInlineEnd',
  'paddingInlineStart',
  'paddingLeft',
  'paddingRight',
  'paddingTop',
  'perspective',
  'perspectiveOrigin',
  'r',
  'right',
  'rowGap',
  'rx',
  'ry',
  'scrollMargin',
  'scrollMarginBlock',
  'scrollMarginBlockEnd',
  'scrollMarginBlockStart',
  'scrollMarginBottom',
  'scrollMarginInline',
  'scrollMarginInlineEnd',
  'scrollMarginInlineStart',
  'scrollMarginLeft',
  'scrollMarginRight',
  'scrollMarginTop',
  'scrollPadding',
  'scrollPaddingBlock',
  'scrollPaddingBlockEnd',
  'scrollPaddingBlockStart',
  'scrollPaddingBottom',
  'scrollPaddingInline',
  'scrollPaddingInlineEnd',
  'scrollPaddingInlineStart',
  'scrollPaddingLeft',
  'scrollPaddingRight',
  'scrollPaddingTop',
  'shapeMargin',
  'strokeDashoffset',
  'strokeWidth',
  'textDecorationThickness',
  'textIndent',
  'textUnderlineOffset',
  'top',
  'transformOrigin',
  'translate',
  'verticalAlign',
  'viewTimelineInset',
  'width',
  'wordSpacing',
  'x',
  'y',
] as const;

export type ZeroLengthProperty = (typeof ZERO_LENGTH_PROPERTIES)[number];

const ZERO_LENGTHS: ReadonlySet<string> = new Set(ZERO_LENGTH_PROPERTIES);

/** Whether a strict scale on `property` admits zero beside its keys. */
export function isZeroLengthProperty(property: string): boolean {
  return ZERO_LENGTHS.has(property);
}
