/**
 * The properties whose value is a single length, as style keys: on a strict
 * scale, zero (`0` or `'0'`) is admitted beside the scale's keys only on
 * these, and elsewhere the scale wins. The strict types read this table, as
 * does the runtime resolver; the extractor reads it through
 * `property_table.json`.
 */
export const ZERO_LENGTH_PROPERTIES = [
  'blockSize',
  'borderBlockEndWidth',
  'borderBlockStartWidth',
  'borderBlockWidth',
  'borderBottomLeftRadius',
  'borderBottomRightRadius',
  'borderBottomWidth',
  'borderEndEndRadius',
  'borderEndStartRadius',
  'borderInlineEndWidth',
  'borderInlineStartWidth',
  'borderInlineWidth',
  'borderLeftWidth',
  'borderRadius',
  'borderRightWidth',
  'borderStartEndRadius',
  'borderStartStartRadius',
  'borderTopLeftRadius',
  'borderTopRightRadius',
  'borderTopWidth',
  'borderWidth',
  'bottom',
  'columnGap',
  'flexBasis',
  'fontSize',
  'gap',
  'height',
  'inlineSize',
  'inset',
  'insetBlock',
  'insetBlockEnd',
  'insetBlockStart',
  'insetInline',
  'insetInlineEnd',
  'insetInlineStart',
  'left',
  'letterSpacing',
  'margin',
  'marginBlock',
  'marginBlockEnd',
  'marginBlockStart',
  'marginBottom',
  'marginInline',
  'marginInlineEnd',
  'marginInlineStart',
  'marginLeft',
  'marginRight',
  'marginTop',
  'maxBlockSize',
  'maxHeight',
  'maxInlineSize',
  'maxWidth',
  'minBlockSize',
  'minHeight',
  'minInlineSize',
  'minWidth',
  'outlineOffset',
  'outlineWidth',
  'padding',
  'paddingBlock',
  'paddingBlockEnd',
  'paddingBlockStart',
  'paddingBottom',
  'paddingInline',
  'paddingInlineEnd',
  'paddingInlineStart',
  'paddingLeft',
  'paddingRight',
  'paddingTop',
  'right',
  'rowGap',
  'scrollMargin',
  'scrollMarginBlock',
  'scrollMarginBottom',
  'scrollMarginInline',
  'scrollMarginLeft',
  'scrollMarginRight',
  'scrollMarginTop',
  'scrollPadding',
  'scrollPaddingBlock',
  'scrollPaddingBottom',
  'scrollPaddingInline',
  'scrollPaddingLeft',
  'scrollPaddingRight',
  'scrollPaddingTop',
  'textDecorationThickness',
  'textIndent',
  'textUnderlineOffset',
  'top',
  'width',
  'wordSpacing',
] as const;

export type ZeroLengthProperty = (typeof ZERO_LENGTH_PROPERTIES)[number];

const ZERO_LENGTHS: ReadonlySet<string> = new Set(ZERO_LENGTH_PROPERTIES);

/** Whether a strict scale on `property` admits zero beside its keys. */
export function isZeroLengthProperty(property: string): boolean {
  return ZERO_LENGTHS.has(property);
}
