name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - run: bun install

      - name: Lint
        run: bun run check

      - name: Type Check
        run: bun run compile

      - name: Build
        run: bun run build

      - name: Test
        run: bun test
