name: Publish
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.PUBLISH }}

      - name: Use NodeJS 14
        uses: actions/setup-node@v2
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_SECRET }}
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'

      - name: Install & Build
        run: |
          yarn install && yarn build-all

      - name: Config GH User
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Prerelease
        run: |
          yarn lerna publish --canary --yes
