name: Publish Beta
on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set User
        run: |
          git config user.name "codecaaron"
          git config user.email "raelaggro@gmail.com"

      - name: Use NodeJS 20
        uses: actions/setup-node@v3
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_SECRET }}
        with:
          node-version: '20.19.0'
          registry-url: 'https://registry.npmjs.org'
          scope: 'animus-ui'

      - name: Install dependencies
        run: |
          yarn && yarn lerna bootstrap

      - name: Unit Tests
        run: yarn test

      - name: Build and Publish
        run: |
          yarn install && yarn build-all
          yarn lerna version --conventional-commits --conventional-prerelease --preid beta --yes
          yarn lerna publish from-git --yes --no-verify-access
