name: Publish Alpha
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        env:
          COMMIT_SHA:
        with:
          fetch-depth: 0
          token: ${{ secrets.PUBLISH }}

      - name: Use NodeJS 14
        uses: actions/setup-node@v2
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_SECRET }}
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'
          scope: 'animus-ui'

      - name: Setup Packages
        run: |
          yarn
          yarn lerna bootstrap
          yarn build-all

      - name: Check Build
        run: |
          yarn verify

      - name: Unit Tests
        run: yarn test

      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Build and Publish
        run: |
          yarn lerna publish --no-verify-access --no-private --canary --yes --preid $SHORT_SHA
